### ISSUE TITLE
Unable to install gem on Wheezy: G_OPTION_FLAG_NONE undeclared

### ISSUE THREAD

**Issue by Type-kun** [r888888888/dtext_rb#15]
While attempting to run bundle install on the most recent Danbooru on Debian Wheezy, it fails with the following in the output:

> make "DESTDIR="
> compiling rb_dtext.c
> compiling dtext.c
> ext/dtext/dtext.rl: In function ‘main’:
> ext/dtext/dtext.rl:1418:27: error: ‘G_OPTION_FLAG_NONE’ undeclared (first use in this function)
> ext/dtext/dtext.rl:1418:27: note: each undeclared identifier is reported only once for each function it appears in
> make: *** [dtext.o] Error 1
> 
> make failed, exit code 2

Curiously, running `gem install dtext_rb -v '1.4.4'` like bundler suggests, executes without any trouble.

**Comment by r888888888** [comment]
Maybe it's the version of glib? I'm using 2.50.3 here.

**Comment by evazion** [comment]
Yeah it was introduced in 2.42 but it looks like wheezy still runs 2.33.
