### ISSUE TITLE
[b] and Other Styling Tags Allow Multiple Levels of Nesting

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/dtext_rb#6]
Demonstrated on Danbooru...

http://danbooru.donmai.us/forum_topics/9127?page=152#forum_post_25578

Not sure what the proper behavior should be.  I'm not in favor of it, but if this is the way it's supposed to work, then I'll just document it in the Wiki.

**Comment by r888888888** [comment]
My belief here is that this is invalid syntax so you shouldn't be surprised by what the parser outputs. That being said, I think the current behavior is sensible and it doesn't seem to break anything.

**Comment by BrokenEagle** [comment]
Got it... I'll update the [Help:DText](http://danbooru.donmai.us/wiki_pages/43047) wiki accordingly.
