### ISSUE TITLE
Allow [code] styling to be inline

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/dtext_rb#9]
Not sure if this used to be a thing with the old DText parser, since the [Help:Blacklists](http://danbooru.donmai.us/wiki_pages/43443) wiki had [code] blocks inline.  For now, I've replaced those with quotation marks, but it would be nice to be able to do code styling inline.

**Comment by r888888888** [comment]
I believe the spoiler tag has this same problem but one issue is how the parser can figure out whether a tag is inline or block. How should the parser handle these scenarios:

`[code]this is a block[/code]`

`this is [code]inline code[/code].`

`[code]this should be inline[/code] too`

The last scenario is what will confuse the parser. Maybe it's uncommon enough to not be a problem but to properly handle it I believe some sort of backtracking is needed.

**Comment by BrokenEagle** [comment]
The **nodtext** tag would also have the same issue as the **spoiler** and **code** tags.

```
[nodtext]This is a block with viewable [b] and [i] tags[/nodtext]

This is [nodtext]inline text with viewable [b] and [i] tags[/nodtext].

[nodtext]This should be inline text with viewable [b] and [i] tags[/nodtext] too.
```

**Comment by evazion** [comment]
As a workaround, you can insert a leading space at the start of the line to force inline context:

```
[code]this is [b]block[/b] context[/code] blah blah

 [code]this is [b]inline[/b] context[/code] blah blah
```

Note also that block `[code]` generates the `<pre>` tag while inline `[code]` generates `<code>`. Danbooru may require some extra CSS for styling inline code tags.
